from flask import Flask, request, jsonify
import pandas as pd
import os
from datetime import datetime

app = Flask(__name__)

EXCEL_PATH = "packaging_inventory.xlsx"

# Store-specific par levels
PAR_LEVELS = {
    "Doncaster": {
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
        
    },
    
    "The Pines": {
       "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    },
    
    "Elwood": {
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    },
    
    "Kew": {
     "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0   


    }, 
    "Tooronga Village": {
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    }, 

    "St Kilda":{
       "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0 
    }, 
    
    "Acland Court":{
        "Small Box": 3,
        "Medium Box": 3, 
        "Large Box": 3,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 3, 
        "Carry Bag": 0, 
        "Bread Clips": 5, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 1, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    }, 
    
    "Moorabbin":{
       "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0 
    }, 
    
    "Queen Victoria Market":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    }, 
    
    "Camberwell":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0 
    }, 
    
    "South Melbourne":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0 
    }, 
    
    "Hampton":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0  
    }, 
    
    "Southland":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0  
    },
    
    "Brighton":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
        
    }, 
    
    "Malvern":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    }, 
    
    "Toorak":{
        "Small Box": 0,
        "Medium Box": 0, 
        "Large Box": 0,
        "Small Pastry Bag": 0,
        "Medium Pastry Bag": 0, 
        "Paper Bread Bag": 0,
        "Plastic Bread Bag": 0, 
        "Small Plastic Bag": 0, 
        "Baguette Bag": 0, 
        "Carry Bag": 0, 
        "Bread Clips": 0, 
        "Butcher Paper": 0, 
        "Silicon Paper": 0, 
        "Small Silicon Paper (pastry cabinet)": 0,
        "Bin Bags": 0, 
        "Gloves": 0, 
        "Hand Towel": 0, 
        "Blue Roll (chux)": 0,
        "Multi Purpose Cleaner": 0, 
        "Floor Cleaner": 0, 
        "Sanitiser": 0, 
        "Window Cleaner": 0, 
        "Sponges":0, 
        "Hand Soap":0,
        "Dishwashing Detergent": 0, 
        "Thermal Register Roll (printer)": 0, 
        "Thermal Register": 0, 
        "Toilet Paper": 0
    },  
}

@app.route("/webhook", methods=["POST"])
def webhook():
    data = request.json
    store = data.get("Store", "Unknown Store")
    stock_data = data.get("Packaging stock take", {})
    par_levels = PAR_LEVELS.get(store, {})

    if not par_levels:
        return jsonify({"error": f"No par levels defined for store: {store}"}), 400

    # Prepare DataFrame (load or initialize)
    if os.path.exists(EXCEL_PATH):
        df = pd.read_excel(EXCEL_PATH)
    else:
        df = pd.DataFrame(columns=["Store", "Timestamp", "Item", "Current Stock", "Par Level", "Low Stock"])

    low_items = {}

    # Parse stock data and compare to par levels
    for item, qty in stock_data.items():
        try:
            qty = float(qty)
            par = par_levels.get(item)
            if par is not None:
                is_low = qty < par
                row = {
                    "Store": store,
                    "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "Item": item,
                    "Current Stock": qty,
                    "Par Level": par,
                    "Low Stock": "Yes" if is_low else "No"
                }
                df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)

                if is_low:
                    low_items[item] = qty
        except ValueError:
            continue  # skip any non-numeric inputs

    df.to_excel(EXCEL_PATH, index=False)

    if low_items:
        print(f"LOW STOCK ({store}):", low_items)

    return jsonify({"status": "updated", "store": store, "low_stock": low_items}), 200
